version: "3.9"

services:
  vk-godeveloper-task:
    build: ./
    command: ./vk-godeveloper-task
    ports:
      - "8080:8080"
    depends_on:
      - film_library

  film_library:
    restart: always
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres